### ISSUE TITLE
Websocket support, how to?

### ISSUE THREAD

**Issue by michael-riha** [centricular/gstcefsrc#13]
@MathieuDuponchelle first of all, great job on this plugin.

I love it because it does not need Wayland as `wpe` so it was "easy" for me 
to compile and use it in a container. 
As I am not a big C/C++ developer (or not even at all) and I already tested a lot of HTML/JS use-cases, I have a question.

How could you/I enable WebSocket support?

As I already said, I tested `threeJS` and a lot of JS/CSS stuff with this plugin also in LIVE and it was perfect, but `WebSockets` is the last missing link for me to build an HTML5/CSS/JS-"graphic engine" for LIVE with this plugin.

I would really appreciate it if you give me a hint, maybe even feasibility?

Thank you in advance, Michael

**Comment by michael-riha** [comment]
🤦‍♂  wrong IP, works like a charm!

**Comment by MathieuDuponchelle** [comment]
@michael-riha , thanks for following up :)
