### ISSUE TITLE
macOS build issue

### ISSUE THREAD

**Issue by mstllc** [centricular/gstcefsrc#14]
Hey there!  Thanks for working on this, it looks like it could be a promising solution to the current problem I'm working on solving :)

Eventually, I'll be running this on a Linux server, but during testing I'm using macOS.  When I run the build steps in the README, things go pretty well until the very end.  The `cmake` command downloads cef and extracts it, and everything seems good with the `cmake` command.  When I run the `make` command, the build process get's through 97% of the process, I see it builds the target `libcef_dll_wrapper` successfully, but then I see these error lines at the end of the build process:

```
[ 97%] Linking CXX static library libcef_dll_wrapper.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper.a(cef_atomicops_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper.a(cef_lock.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper.a(libcef_dll_wrapper2.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper.a(cef_atomicops_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper.a(cef_lock.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper.a(libcef_dll_wrapper2.cc.o) has no symbols
[ 97%] Built target libcef_dll_wrapper
Scanning dependencies of target gstcef
[ 97%] Building CXX object CMakeFiles/gstcef.dir/gstcef.cc.o
[ 98%] Building CXX object CMakeFiles/gstcef.dir/gstcefsrc.cc.o
[ 98%] Building CXX object CMakeFiles/gstcef.dir/gstcefdemux.cc.o
[ 99%] Building CXX object CMakeFiles/gstcef.dir/gstcefaudiometa.cc.o
make[2]: *** No rule to make target `libcef_lib-NOTFOUND', needed by `Release/libgstcef.dylib'.  Stop.
make[1]: *** [CMakeFiles/gstcef.dir/all] Error 2
make: *** [all] Error 2
```

Any idea if there are some different steps I need to take to get this up and running on macOS?  I don't have a lot of experience with cef, so maybe it's something I need to do differently in regard to building that?

Any help or pointers would be greatly appreciated!  Thanks again!

**Comment by MathieuDuponchelle** [comment]
I don't necessarily have an idea either, I don't have much experience with cmake I'm afraid. fwiw this element has only been tested / built on windows and linux, so I'm not too surprised that there would be a build issue on OSX. Please do let me know if you find a fix though :)

**Comment by mstllc** [comment]
No problem, thanks for following up!  I have setup Linux in a virtual machine and was able to get the plugin running there, so for now, I'll probably continue down that path.  If I end up coming back around to trying to get it working on macOS I will definitely let you know and open a PR if I have a good solution.

Thanks again, closing for now.

**Comment by MathieuDuponchelle** [comment]
@mstllc good to hear :) Few things worth noting about the plugin:

* audio capture relies on API that was merged then removed in cef, so for now we're stuck with an older version of CEF. https://bitbucket.org/chromiumembedded/cef/issues/2755/reimplement-audio-mirroring-for for context. 

* The plugin needs a `GMainContext` to be running, this piece of code: https://github.com/centricular/gstcefsrc/blob/master/gstcefsrc.cc#L231-L239 ideally needs replacing, but CEF's API is a bit obscure and that was the simple solution

* You may want to check out `wpesrc`: https://gstreamer.freedesktop.org/documentation/wpe/index.html?gi-language=c , I don't think it has audio support yet however (https://github.com/Igalia/WPEBackend-fdo/pull/100 is related)

**Comment by philn** [comment]
I have a WIP branch for audio support in gstwpe: https://gitlab.freedesktop.org/philn/gst-plugins-bad/-/tree/wpe-audio which depends on https://bugs.webkit.org/show_bug.cgi?id=207634 as well.

**Comment by reinismu** [comment]
I just got a need to get cefsrc working under MacOS as I need accelerated ProRes encoder.

@mstllc did you mange to get MacOS working in the end?

Will see if I get to root cause of why project doesn't build under MacOS and if I can fix it

**Comment by reinismu** [comment]
Seems like this is the answer https://bitbucket.org/chromiumembedded/cef/src/25c75c5fc4fc7d7fbdebdf20ca56ab3162eab570/tests/cefsimple/CMakeLists.txt.in#lines-89
Need to configure Cmake to work for macos. I guess will give it a shot and see how far I get

**Comment by MathieuDuponchelle** [comment]
Hey @reinismu , sorry I'm at the gst hackfest, just noticed your messages. I'm OK with reopening the issue if there is a WIP branch to iterate from, your comment here will be a bit buried though, might be best to open a whole new one?
