### ISSUE TITLE
[question] h264 CEF?

### ISSUE THREAD

**Issue by ldenoue** [centricular/gstcefsrc#29]
How could we use a build of CEF that has all codecs, like H264?

I noticed this commit changin remote port numbers, but is there one to tell CEF to use a different Chromium build? Or has CEF to be built completely from scratch?

**Comment by MathieuDuponchelle** [comment]
you need to build CEF from scratch I'm afraid:

https://stackoverflow.com/questions/64293697/enable-aac-support-in-chromium-embedded-framework-c

Good luck because it's an absolute PITA :P

**Comment by reinismu** [comment]
It's not so bad, I managed to do it in a day. I could link to binaries, but it is in my S3 and I don't want to pay for aws too much :D 

@ldenoue Here is the docker and scripts how to do it. Should be pretty simple to do

**Comment by MathieuDuponchelle** [comment]
@reinismu did you forget to link your scripts?

**Comment by reinismu** [comment]
> @reinismu did you forget to link your scripts?

Yup :D Added link

**Comment by ldenoue** [comment]
@reinismu thanks a lot! I'll try your scripts.
Laurent
