### ISSUE TITLE
RTMP SINK GSTREAMER 

### ISSUE THREAD

**Issue by ghizlane-code** [centricular/gstcefsrc#4]
Hello,

In order to send the video and audio from the cefsrc module to facebook or twitch , i'm using this gstreamer pipeline:

```
gst-launch-1.0 cefsrc url="file:///home/…." ! queue ! 
cefdemux name=d d.video ! video/x-raw,format=BGRA,width=1280,height=720,framerate=30/1 ! queue !
videoconvert ! videorate max-rate=3000 ! videoscale ! x264enc tune=zerolatency speed-preset=superfast key-int-max=60 ref=2 !
mux. d.audio_0 ! 
audio/x-raw,rate=48000 ! queue ! audioconvert ! audiorate ! voaacenc bitrate=96000 ! 
flvmux streamable=true name=mux ! queue ! 
rtmpsink location="rtmps://live-api-s.facebook.com:443/rtmp/<facebook key> live=1"
```

Therefore, it does not connect to facebook (offline status)
On the other hand, when I send the video of the cefsrc module and a test audio as follows:

```
gst-launch-1.0 cefsrc url="file:///home/…." ! queue ! 
cefdemux name=d d.video ! video/x-raw,format=BGRA,width=1280,height=720,framerate=30/1 ! queue !
videoconvert ! videorate max-rate=3000 ! videoscale ! x264enc tune=zerolatency speed-preset=superfast key-int-max=60 ref=2 !
mux. audiotestsrc ! 
audio/x-raw,rate=48000 ! queue ! audioconvert ! audiorate ! voaacenc bitrate=96000 ! 
flvmux streamable=true name=mux ! queue ! 
rtmpsink location="rtmps://live-api-s.facebook.com:443/rtmp/<facebook key> live=1"
```

I can see the video and I hear the sound of audiotestsrc.

Is there anyone who would have a gstreamer based functional pipeline to push an Audio + Video muxed stream, of cefsrc module, using the rtmpsink module.

Thank you

Best regards

**Comment by MathieuDuponchelle** [comment]
Hello @ghizlane-code .

This is the second time you open an issue here for a general GStreamer support question, I would like you to not do that again.

As the first time, I will close this issue and redirect you to GStreamers' mailing list / IRC.

Thanks

**Comment by ghizlane-code** [comment]
THANK YOU FOR YOUR REPLY @MathieuDuponchelle 

I appreciate your feedback but do not you think it would have been more effective if it had been constructive?

Your answer shows that you are mature and VERY PROFESSIONAL.

Well done.

**Comment by ezerbib** [comment]
I have the same problem, some investigation show that the compilation of rtmpsink is based on librtmp which is compiled with gnutls,  the code of gnutls_handshake has change and can return  non-fatal errors such as   GNUTLS_E_INTERRUPTED, GNUTLS_E_AGAIN,... 
definitly the code of librtmp is too old and doesn't fit with facebook server

**Comment by nirbheek** [comment]
>  definitly the code of librtmp is too old and doesn't fit with facebook server

Yes, librtmp is not maintained by upstream, which is why the rtmp2 plugin was written which does not use librtmp. You should try using that and [report any issues upstream](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/new). Please note that in general issue trackers are for tracking issues. Support requests should go to the [gstreamer-devel mailing list](https://gstreamer.freedesktop.org/lists/) or to #gstreamer on FreeNode IRC.

Again -- please do not use this issue tracker for general gstreamer issues not related to gstcefsrc. :slightly_smiling_face:
