### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by heftig** [centricular/gstcefsrc#44]
Is it possible to enable the sandbox?

**Comment by reinismu** [comment]
I think it should be, might need to recompile with correct flags, tho haven't tried it.

Out of curiosity, why do you want to sandbox?

**Comment by heftig** [comment]
It seemed like low-hanging security fruit.

**Comment by MathieuDuponchelle** [comment]
The sandbox is disabled here: https://github.com/centricular/gstcefsrc/blob/master/gstcefsrc.cc#L416 . I've never tried, but maybe just remove that line and see what happens? :)

**Comment by heftig** [comment]
I tried that. Unfortunately in our Docker containers, `gst-launch-1.0 cefsrc ! fakesink` as "root" just exits. Retrying with another user results in a SIGTRAP instead.

**Comment by heftig** [comment]
That does seem to work in a Docker container, assuming it is privileged (so it can create namespaces) and the application does not run as root.

**Comment by MathieuDuponchelle** [comment]
@heftig , is there anything more we should do here, or can this be closed?
